---
abstract: 'Dist::Zilla configuration the way YAKEX does it'
author:
  - 'Yasutaka ATARASHI <yakex@cpan.org>'
build_requires:
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-YAKEX
no_index:
  directory:
    - profiles
requires:
  Dist::Zilla: 0
  Dist::Zilla::Plugin::Bootstrap::lib: 0
  Dist::Zilla::Plugin::CheckVersionIncrement: 0
  Dist::Zilla::Plugin::GithubMeta: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MinimumPerl: 0
  Dist::Zilla::Plugin::NextRelease: 0
  Dist::Zilla::Plugin::OurPkgVersion: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0
  Dist::Zilla::Plugin::Test::Compile: 2.027
  Dist::Zilla::Plugin::Test::Kwalitee::Extra: v0.1.3
  Dist::Zilla::Plugin::Test::Perl::Critic: 0
  Dist::Zilla::Plugin::Twitter: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle::PluginRemover: 0
  Moose: 0
  perl: 5.006
resources:
  homepage: https://github.com/yak1ex/Dist-Zilla-PluginBundle-Author-YAKEX
  repository: https://github.com/yak1ex/Dist-Zilla-PluginBundle-Author-YAKEX.git
version: v0.1.0
